// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 31.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `protos/extensions.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:v2ray.core.common.protoext.MessageOpt)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct MessageOpt {
    // message fields
    // @@protoc_insertion_point(field:v2ray.core.common.protoext.MessageOpt.type)
    pub type_: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:v2ray.core.common.protoext.MessageOpt.short_name)
    pub short_name: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:v2ray.core.common.protoext.MessageOpt.transport_original_name)
    pub transport_original_name: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:v2ray.core.common.protoext.MessageOpt.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MessageOpt {
    fn default() -> &'a MessageOpt {
        <MessageOpt as ::protobuf::Message>::default_instance()
    }
}

impl MessageOpt {
    pub fn new() -> MessageOpt {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "type",
            |m: &MessageOpt| { &m.type_ },
            |m: &mut MessageOpt| { &mut m.type_ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "short_name",
            |m: &MessageOpt| { &m.short_name },
            |m: &mut MessageOpt| { &mut m.short_name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "transport_original_name",
            |m: &MessageOpt| { &m.transport_original_name },
            |m: &mut MessageOpt| { &mut m.transport_original_name },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<MessageOpt>(
            "MessageOpt",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for MessageOpt {
    const NAME: &'static str = "MessageOpt";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.type_.push(is.read_string()?);
                },
                18 => {
                    self.short_name.push(is.read_string()?);
                },
                688010 => {
                    self.transport_original_name = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.type_ {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        for value in &self.short_name {
            my_size += ::protobuf::rt::string_size(2, &value);
        };
        if !self.transport_original_name.is_empty() {
            my_size += ::protobuf::rt::string_size(86001, &self.transport_original_name);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.type_ {
            os.write_string(1, &v)?;
        };
        for v in &self.short_name {
            os.write_string(2, &v)?;
        };
        if !self.transport_original_name.is_empty() {
            os.write_string(86001, &self.transport_original_name)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MessageOpt {
        MessageOpt::new()
    }

    fn clear(&mut self) {
        self.type_.clear();
        self.short_name.clear();
        self.transport_original_name.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MessageOpt {
        static instance: MessageOpt = MessageOpt {
            type_: ::std::vec::Vec::new(),
            short_name: ::std::vec::Vec::new(),
            transport_original_name: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for MessageOpt {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("MessageOpt").unwrap()).clone()
    }
}

impl ::std::fmt::Display for MessageOpt {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MessageOpt {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:v2ray.core.common.protoext.FieldOpt)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct FieldOpt {
    // message fields
    // @@protoc_insertion_point(field:v2ray.core.common.protoext.FieldOpt.any_wants)
    pub any_wants: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:v2ray.core.common.protoext.FieldOpt.allowed_values)
    pub allowed_values: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:v2ray.core.common.protoext.FieldOpt.allowed_value_types)
    pub allowed_value_types: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:v2ray.core.common.protoext.FieldOpt.convert_time_read_file_into)
    pub convert_time_read_file_into: ::std::string::String,
    // @@protoc_insertion_point(field:v2ray.core.common.protoext.FieldOpt.forbidden)
    pub forbidden: bool,
    // @@protoc_insertion_point(field:v2ray.core.common.protoext.FieldOpt.convert_time_resource_loading)
    pub convert_time_resource_loading: ::std::string::String,
    // @@protoc_insertion_point(field:v2ray.core.common.protoext.FieldOpt.convert_time_parse_ip)
    pub convert_time_parse_ip: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:v2ray.core.common.protoext.FieldOpt.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a FieldOpt {
    fn default() -> &'a FieldOpt {
        <FieldOpt as ::protobuf::Message>::default_instance()
    }
}

impl FieldOpt {
    pub fn new() -> FieldOpt {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(7);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "any_wants",
            |m: &FieldOpt| { &m.any_wants },
            |m: &mut FieldOpt| { &mut m.any_wants },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "allowed_values",
            |m: &FieldOpt| { &m.allowed_values },
            |m: &mut FieldOpt| { &mut m.allowed_values },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "allowed_value_types",
            |m: &FieldOpt| { &m.allowed_value_types },
            |m: &mut FieldOpt| { &mut m.allowed_value_types },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "convert_time_read_file_into",
            |m: &FieldOpt| { &m.convert_time_read_file_into },
            |m: &mut FieldOpt| { &mut m.convert_time_read_file_into },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "forbidden",
            |m: &FieldOpt| { &m.forbidden },
            |m: &mut FieldOpt| { &mut m.forbidden },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "convert_time_resource_loading",
            |m: &FieldOpt| { &m.convert_time_resource_loading },
            |m: &mut FieldOpt| { &mut m.convert_time_resource_loading },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "convert_time_parse_ip",
            |m: &FieldOpt| { &m.convert_time_parse_ip },
            |m: &mut FieldOpt| { &mut m.convert_time_parse_ip },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<FieldOpt>(
            "FieldOpt",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for FieldOpt {
    const NAME: &'static str = "FieldOpt";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.any_wants.push(is.read_string()?);
                },
                18 => {
                    self.allowed_values.push(is.read_string()?);
                },
                26 => {
                    self.allowed_value_types.push(is.read_string()?);
                },
                34 => {
                    self.convert_time_read_file_into = is.read_string()?;
                },
                40 => {
                    self.forbidden = is.read_bool()?;
                },
                50 => {
                    self.convert_time_resource_loading = is.read_string()?;
                },
                58 => {
                    self.convert_time_parse_ip = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.any_wants {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        for value in &self.allowed_values {
            my_size += ::protobuf::rt::string_size(2, &value);
        };
        for value in &self.allowed_value_types {
            my_size += ::protobuf::rt::string_size(3, &value);
        };
        if !self.convert_time_read_file_into.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.convert_time_read_file_into);
        }
        if self.forbidden != false {
            my_size += 1 + 1;
        }
        if !self.convert_time_resource_loading.is_empty() {
            my_size += ::protobuf::rt::string_size(6, &self.convert_time_resource_loading);
        }
        if !self.convert_time_parse_ip.is_empty() {
            my_size += ::protobuf::rt::string_size(7, &self.convert_time_parse_ip);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.any_wants {
            os.write_string(1, &v)?;
        };
        for v in &self.allowed_values {
            os.write_string(2, &v)?;
        };
        for v in &self.allowed_value_types {
            os.write_string(3, &v)?;
        };
        if !self.convert_time_read_file_into.is_empty() {
            os.write_string(4, &self.convert_time_read_file_into)?;
        }
        if self.forbidden != false {
            os.write_bool(5, self.forbidden)?;
        }
        if !self.convert_time_resource_loading.is_empty() {
            os.write_string(6, &self.convert_time_resource_loading)?;
        }
        if !self.convert_time_parse_ip.is_empty() {
            os.write_string(7, &self.convert_time_parse_ip)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> FieldOpt {
        FieldOpt::new()
    }

    fn clear(&mut self) {
        self.any_wants.clear();
        self.allowed_values.clear();
        self.allowed_value_types.clear();
        self.convert_time_read_file_into.clear();
        self.forbidden = false;
        self.convert_time_resource_loading.clear();
        self.convert_time_parse_ip.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static FieldOpt {
        static instance: FieldOpt = FieldOpt {
            any_wants: ::std::vec::Vec::new(),
            allowed_values: ::std::vec::Vec::new(),
            allowed_value_types: ::std::vec::Vec::new(),
            convert_time_read_file_into: ::std::string::String::new(),
            forbidden: false,
            convert_time_resource_loading: ::std::string::String::new(),
            convert_time_parse_ip: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for FieldOpt {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("FieldOpt").unwrap()).clone()
    }
}

impl ::std::fmt::Display for FieldOpt {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FieldOpt {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Extension fields
pub mod exts {

    pub const message_opt: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, super::MessageOpt> = ::protobuf::ext::ExtFieldOptional::new(50000, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_MESSAGE);

    pub const field_opt: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, super::FieldOpt> = ::protobuf::ext::ExtFieldOptional::new(50000, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_MESSAGE);
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x17protos/extensions.proto\x12\x1av2ray.core.common.protoext\x1a\x20g\
    oogle/protobuf/descriptor.proto\"y\n\nMessageOpt\x12\x12\n\x04type\x18\
    \x01\x20\x03(\tR\x04type\x12\x1d\n\nshort_name\x18\x02\x20\x03(\tR\tshor\
    tName\x128\n\x17transport_original_name\x18\xf1\x9f\x05\x20\x01(\tR\x15t\
    ransportOriginalName\"\xd0\x02\n\x08FieldOpt\x12\x1b\n\tany_wants\x18\
    \x01\x20\x03(\tR\x08anyWants\x12%\n\x0eallowed_values\x18\x02\x20\x03(\t\
    R\rallowedValues\x12.\n\x13allowed_value_types\x18\x03\x20\x03(\tR\x11al\
    lowedValueTypes\x12<\n\x1bconvert_time_read_file_into\x18\x04\x20\x01(\t\
    R\x17convertTimeReadFileInto\x12\x1c\n\tforbidden\x18\x05\x20\x01(\x08R\
    \tforbidden\x12A\n\x1dconvert_time_resource_loading\x18\x06\x20\x01(\tR\
    \x1aconvertTimeResourceLoading\x121\n\x15convert_time_parse_ip\x18\x07\
    \x20\x01(\tR\x12convertTimeParseIp:j\n\x0bmessage_opt\x18\xd0\x86\x03\
    \x20\x01(\x0b2&.v2ray.core.common.protoext.MessageOpt\x12\x1f.google.pro\
    tobuf.MessageOptionsR\nmessageOpt:b\n\tfield_opt\x18\xd0\x86\x03\x20\x01\
    (\x0b2$.v2ray.core.common.protoext.FieldOpt\x12\x1d.google.protobuf.Fiel\
    dOptionsR\x08fieldOptBo\n\x1ecom.v2ray.core.common.protoextP\x01Z.github\
    .com/v2fly/v2ray-core/v5/common/protoext\xaa\x02\x1aV2Ray.Core.Common.Pr\
    otoExtb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(::protobuf::descriptor::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(MessageOpt::generated_message_descriptor_data());
            messages.push(FieldOpt::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
